"""Lifecycle utility for Agent Space.

Commands:
- start backend + frontend
- stop backend/frontend
- open UI in browser
- start desktop app shell
- create desktop shortcuts
"""

from __future__ import annotations

import argparse
import json
import os
import secrets
import shlex
import signal
import shutil
import socket
import subprocess
import sys
import time
import webbrowser
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
BACKEND_DIR = REPO_ROOT / "backend"
FRONTEND_DIR = REPO_ROOT / "frontend"
DESKTOP_MAIN = REPO_ROOT / "desktop" / "main.cjs"
PID_FILE = REPO_ROOT / "data" / "agent_space" / "runtime" / "pids.json"
FREE_STACK_DIR = REPO_ROOT / "infra" / "free-stack"
FREE_STACK_COMPOSE = FREE_STACK_DIR / "docker-compose.yml"
SECURE_DIR = REPO_ROOT / "data" / "agent_space" / "secure"
FREE_STACK_ENV_FILE = SECURE_DIR / "free-stack.env"
FREE_STACK_CREDS_FILE = SECURE_DIR / "free-stack-credentials.txt"
FREE_STACK_ALL_SECRETS_FILE = SECURE_DIR / "all-local-secrets.txt"
LEGACY_FREE_STACK_ENV_FILE = REPO_ROOT / "data" / "agent_space" / "runtime" / "free-stack.env"
LEGACY_FREE_STACK_CREDS_FILE = REPO_ROOT / "data" / "agent_space" / "runtime" / "free-stack-credentials.txt"
FREE_STACK_PROJECT = "jimai-free"

FREE_STACK_DEFAULTS = {
    "POSTGRES_DB": "agentspace",
    "POSTGRES_USER": "agentspace",
    "POSTGRES_PASSWORD": "",
    "POSTGRES_PORT": "15432",
    "PGADMIN_DEFAULT_EMAIL": "admin@jimai.app",
    "PGADMIN_DEFAULT_PASSWORD": "",
    "PGADMIN_PORT": "15050",
    "REDIS_PASSWORD": "",
    "REDIS_PORT": "16379",
    "REDIS_COMMANDER_USER": "admin",
    "REDIS_COMMANDER_PASSWORD": "",
    "REDIS_COMMANDER_PORT": "18081",
    "MINIO_ROOT_USER": "minioadmin",
    "MINIO_ROOT_PASSWORD": "",
    "MINIO_API_PORT": "19000",
    "MINIO_CONSOLE_PORT": "19001",
    "GRAFANA_ADMIN_USER": "admin",
    "GRAFANA_ADMIN_PASSWORD": "",
    "GRAFANA_PORT": "13000",
    "PROMETHEUS_PORT": "19090",
    "LOKI_PORT": "13100",
    "QDRANT_PORT": "16333",
    "QDRANT_API_KEY": "",
    "SEARXNG_PORT": "18082",
    "GOTIFY_DEFAULTUSER_NAME": "admin",
    "GOTIFY_DEFAULTUSER_PASS": "",
    "GOTIFY_PORT": "18080",
}


def ensure_runtime_dir() -> None:
    PID_FILE.parent.mkdir(parents=True, exist_ok=True)
    ensure_secure_dir()


def ensure_secure_dir() -> None:
    SECURE_DIR.mkdir(parents=True, exist_ok=True)


def _restrict_file_permissions(path: Path) -> None:
    # Best-effort local hardening. On Windows, chmod is limited but still reduces accidental access.
    try:
        os.chmod(path, 0o600)
    except OSError:
        pass


def _cleanup_legacy_secret_files() -> None:
    for old_path in (LEGACY_FREE_STACK_ENV_FILE, LEGACY_FREE_STACK_CREDS_FILE):
        try:
            if old_path.exists():
                old_path.unlink()
        except OSError:
            pass


def _random_secret(length: int = 26) -> str:
    raw = secrets.token_urlsafe(max(20, length))
    return raw[:length]


def _parse_env_file(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    data: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        data[key.strip()] = value.strip()
    return data


def _write_env_file(path: Path, env_map: dict[str, str]) -> None:
    lines = ["# Auto-generated by scripts/agentspace_lifecycle.py"]
    for key in sorted(env_map.keys()):
        lines.append(f"{key}={env_map[key]}")
    ensure_secure_dir()
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    _restrict_file_permissions(path)


def _ensure_free_stack_env(force_rotate_passwords: bool = False) -> dict[str, str]:
    current = _parse_env_file(FREE_STACK_ENV_FILE)
    merged = dict(FREE_STACK_DEFAULTS)
    merged.update({k: v for k, v in current.items() if k in merged and str(v).strip()})
    pgadmin_email = str(merged.get("PGADMIN_DEFAULT_EMAIL", "")).strip().lower()
    if not pgadmin_email or pgadmin_email.endswith(".local"):
        merged["PGADMIN_DEFAULT_EMAIL"] = FREE_STACK_DEFAULTS["PGADMIN_DEFAULT_EMAIL"]

    secret_keys = (
        "POSTGRES_PASSWORD",
        "PGADMIN_DEFAULT_PASSWORD",
        "REDIS_PASSWORD",
        "REDIS_COMMANDER_PASSWORD",
        "MINIO_ROOT_PASSWORD",
        "GRAFANA_ADMIN_PASSWORD",
        "QDRANT_API_KEY",
        "GOTIFY_DEFAULTUSER_PASS",
    )
    for key in secret_keys:
        if force_rotate_passwords or not str(merged.get(key, "")).strip():
            merged[key] = _random_secret()

    _write_env_file(FREE_STACK_ENV_FILE, merged)
    _write_free_stack_credentials(merged)
    _write_all_local_secrets(merged)
    _cleanup_legacy_secret_files()
    return merged


def _write_free_stack_credentials(env_map: dict[str, str]) -> None:
    lines = [
        "jimAI Free Local Stack Credentials",
        f"Generated: {time.strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "Use these URLs in your browser and sign in with credentials below.",
        "",
        f"Grafana: http://localhost:{env_map['GRAFANA_PORT']}",
        f"  username: {env_map['GRAFANA_ADMIN_USER']}",
        f"  password: {env_map['GRAFANA_ADMIN_PASSWORD']}",
        "",
        f"MinIO Console: http://localhost:{env_map['MINIO_CONSOLE_PORT']}",
        f"  username: {env_map['MINIO_ROOT_USER']}",
        f"  password: {env_map['MINIO_ROOT_PASSWORD']}",
        "",
        f"pgAdmin: http://localhost:{env_map['PGADMIN_PORT']}",
        f"  email: {env_map['PGADMIN_DEFAULT_EMAIL']}",
        f"  password: {env_map['PGADMIN_DEFAULT_PASSWORD']}",
        "",
        f"Redis Commander: http://localhost:{env_map['REDIS_COMMANDER_PORT']}",
        f"  username: {env_map['REDIS_COMMANDER_USER']}",
        f"  password: {env_map['REDIS_COMMANDER_PASSWORD']}",
        "",
        f"Gotify: http://localhost:{env_map['GOTIFY_PORT']}",
        f"  username: {env_map['GOTIFY_DEFAULTUSER_NAME']}",
        f"  password: {env_map['GOTIFY_DEFAULTUSER_PASS']}",
        "",
        f"Qdrant Dashboard: http://localhost:{env_map['QDRANT_PORT']}/dashboard",
        f"  api key: {env_map['QDRANT_API_KEY']}",
        "",
        f"SearXNG: http://localhost:{env_map['SEARXNG_PORT']}",
        "  no login required (local meta-search endpoint)",
        "",
        "Infra ports:",
        f"  Postgres: localhost:{env_map['POSTGRES_PORT']}",
        f"  Redis: localhost:{env_map['REDIS_PORT']}",
        f"  MinIO API: localhost:{env_map['MINIO_API_PORT']}",
        f"  Prometheus: localhost:{env_map['PROMETHEUS_PORT']}",
        f"  Loki: localhost:{env_map['LOKI_PORT']}",
    ]
    ensure_secure_dir()
    FREE_STACK_CREDS_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    _restrict_file_permissions(FREE_STACK_CREDS_FILE)


def _write_all_local_secrets(env_map: dict[str, str]) -> None:
    lines = [
        "jimAI Local Secrets Bundle",
        f"Generated: {time.strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "This file centralizes all generated local credentials and secret env values.",
        "",
        f"Credentials file: {FREE_STACK_CREDS_FILE}",
        "",
        "[ENV]",
    ]
    for key in sorted(env_map.keys()):
        lines.append(f"{key}={env_map[key]}")
    ensure_secure_dir()
    FREE_STACK_ALL_SECRETS_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    _restrict_file_permissions(FREE_STACK_ALL_SECRETS_FILE)


def _detect_compose_base() -> list[str]:
    candidates: list[list[str]] = [
        ["docker", "compose"],
        ["docker-compose"],
        ["podman", "compose"],
        ["podman-compose"],
    ]
    for base in candidates:
        try:
            probe = subprocess.run(
                [*base, "version"],
                cwd=REPO_ROOT,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                timeout=20,
                check=False,
            )
        except (OSError, FileNotFoundError, subprocess.TimeoutExpired):
            continue
        if probe.returncode == 0:
            return base
    raise SystemExit(
        "No supported container compose runtime found.\n"
        "Install one of: Docker (with compose plugin), docker-compose, Podman (compose), or podman-compose.\n"
        "Windows examples:\n"
        "  winget install Docker.DockerDesktop\n"
        "  winget install RedHat.Podman-Desktop"
    )


def _run_compose(base: list[str], compose_args: list[str], *, env_file: Path) -> subprocess.CompletedProcess:
    cmd = [*base, "--env-file", str(env_file), "-f", str(FREE_STACK_COMPOSE), "-p", FREE_STACK_PROJECT, *compose_args]
    compose_env = os.environ.copy()
    compose_env.update(_parse_env_file(env_file))
    return subprocess.run(cmd, cwd=REPO_ROOT, env=compose_env, text=True, check=False)


def _open_url(url: str) -> None:
    if os.name == "nt":
        try:
            os.startfile(url)  # type: ignore[attr-defined]
            return
        except OSError:
            pass
    webbrowser.open(url)


def _shortcut_python_executable() -> str:
    venv_python = REPO_ROOT / "backend" / ".venv" / "Scripts" / "python.exe"
    if venv_python.exists():
        return r"backend\.venv\Scripts\python.exe"
    return "python"


def _lifecycle_cmd(args: str) -> str:
    python_bin = _shortcut_python_executable()
    if args.strip():
        return f"\"{python_bin}\" scripts\\agentspace_lifecycle.py {args}"
    return f"\"{python_bin}\" scripts\\agentspace_lifecycle.py"


def _open_free_stack_urls(env_map: dict[str, str]) -> None:
    urls = [
        f"http://localhost:{env_map['GRAFANA_PORT']}",
        f"http://localhost:{env_map['MINIO_CONSOLE_PORT']}",
        f"http://localhost:{env_map['PGADMIN_PORT']}",
        f"http://localhost:{env_map['REDIS_COMMANDER_PORT']}",
        f"http://localhost:{env_map['GOTIFY_PORT']}",
        f"http://localhost:{env_map['QDRANT_PORT']}/dashboard",
        f"http://localhost:{env_map['SEARXNG_PORT']}",
    ]
    for url in urls:
        _open_url(url)
    print("Opened free stack dashboards in browser.")


def _create_free_stack_shortcuts(env_map: dict[str, str]) -> None:
    desktop = Path.home() / "Desktop"
    output_dir = desktop
    try:
        output_dir.mkdir(parents=True, exist_ok=True)
    except Exception:
        output_dir = REPO_ROOT / "data" / "agent_space" / "runtime" / "desktop_shortcuts"
        output_dir.mkdir(parents=True, exist_ok=True)
    commands = {
        "jimAI - Free Stack Setup.cmd": _lifecycle_cmd("free-stack-setup --start --open --shortcuts"),
        "jimAI - Install Podman Runtime.cmd": _lifecycle_cmd("free-stack-install-runtime --runtime podman"),
        "jimAI - Install Docker Runtime.cmd": _lifecycle_cmd("free-stack-install-runtime --runtime docker"),
        "jimAI - Free Stack Start.cmd": _lifecycle_cmd("free-stack-start --open"),
        "jimAI - Free Stack Stop.cmd": _lifecycle_cmd("free-stack-stop"),
        "jimAI - Free Stack Open Dashboards.cmd": _lifecycle_cmd("free-stack-open"),
        "jimAI - Launch Desktop + Free Stack.cmd": f"{_lifecycle_cmd('free-stack-start')} && {_lifecycle_cmd('desktop --with-services')}",
    }
    for filename, command in commands.items():
        content = f"@echo off\r\ncd /d \"{REPO_ROOT}\"\r\n{command}\r\n"
        try:
            (output_dir / filename).write_text(content, encoding="utf-8")
        except PermissionError:
            fallback = REPO_ROOT / "data" / "agent_space" / "runtime" / "desktop_shortcuts"
            fallback.mkdir(parents=True, exist_ok=True)
            (fallback / filename).write_text(content, encoding="utf-8")
            output_dir = fallback

    desktop_creds = output_dir / "jimAI - Free Stack Credentials.txt"
    lines = [
        "jimAI Free Stack Login Shortcuts",
        "",
        f"Grafana: http://localhost:{env_map['GRAFANA_PORT']}",
        f"MinIO Console: http://localhost:{env_map['MINIO_CONSOLE_PORT']}",
        f"pgAdmin: http://localhost:{env_map['PGADMIN_PORT']}",
        f"Redis Commander: http://localhost:{env_map['REDIS_COMMANDER_PORT']}",
        f"Gotify: http://localhost:{env_map['GOTIFY_PORT']}",
        f"Qdrant Dashboard: http://localhost:{env_map['QDRANT_PORT']}/dashboard",
        f"SearXNG: http://localhost:{env_map['SEARXNG_PORT']}",
        "",
        f"Credentials source: {FREE_STACK_CREDS_FILE}",
    ]
    desktop_creds.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Created free stack desktop launchers in {output_dir}")


def _print_free_stack_credential_summary(env_map: dict[str, str]) -> None:
    print("Free stack is configured with local accounts:")
    print(f"  Grafana:         http://localhost:{env_map['GRAFANA_PORT']}  ({env_map['GRAFANA_ADMIN_USER']})")
    print(f"  MinIO Console:   http://localhost:{env_map['MINIO_CONSOLE_PORT']}  ({env_map['MINIO_ROOT_USER']})")
    print(f"  pgAdmin:         http://localhost:{env_map['PGADMIN_PORT']}  ({env_map['PGADMIN_DEFAULT_EMAIL']})")
    print(f"  Redis Commander: http://localhost:{env_map['REDIS_COMMANDER_PORT']}  ({env_map['REDIS_COMMANDER_USER']})")
    print(f"  Gotify:          http://localhost:{env_map['GOTIFY_PORT']}  ({env_map['GOTIFY_DEFAULTUSER_NAME']})")
    print(f"  Qdrant Dashboard:http://localhost:{env_map['QDRANT_PORT']}/dashboard")
    print(f"  SearXNG:         http://localhost:{env_map['SEARXNG_PORT']}")
    print(f"  Full credentials saved to: {FREE_STACK_CREDS_FILE}")
    print(f"  All secrets bundle saved to: {FREE_STACK_ALL_SECRETS_FILE}")


def load_pids() -> dict:
    if not PID_FILE.exists():
        return {}
    try:
        return json.loads(PID_FILE.read_text(encoding="utf-8"))
    except Exception:
        return {}


def save_pids(data: dict) -> None:
    ensure_runtime_dir()
    PID_FILE.write_text(json.dumps(data, indent=2), encoding="utf-8")


def is_running(pid: int) -> bool:
    try:
        os.kill(pid, 0)
    except OSError:
        return False
    return True


def terminate_pid(pid: int) -> bool:
    if not pid:
        return False
    try:
        os.kill(pid, signal.SIGTERM)
        return True
    except OSError:
        return False


def _wait_for_tcp_ready(
    name: str,
    host: str,
    port: int,
    timeout_seconds: float,
    proc: subprocess.Popen | None = None,
) -> tuple[bool, str]:
    probe_host = "127.0.0.1" if host in {"0.0.0.0", "::"} else host
    deadline = time.time() + timeout_seconds
    while time.time() < deadline:
        if proc is not None and proc.poll() is not None:
            return False, f"{name} exited early (code {proc.returncode})."
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        try:
            sock.settimeout(0.4)
            if sock.connect_ex((probe_host, int(port))) == 0:
                return True, ""
        except OSError:
            pass
        finally:
            sock.close()
        time.sleep(0.2)
    return False, f"{name} did not open tcp://{probe_host}:{port} within {timeout_seconds:.0f}s."


def choose_backend_python() -> str:
    venv_python = BACKEND_DIR / ".venv" / "Scripts" / "python.exe"
    if venv_python.exists():
        return str(venv_python)
    return sys.executable


def choose_tool(name: str) -> str:
    if os.name == "nt":
        local_bin = REPO_ROOT / "node_modules" / ".bin" / f"{name}.cmd"
        if local_bin.exists():
            return str(local_bin)
    if os.name == "nt":
        win = shutil.which(f"{name}.cmd")
        if win:
            return win
    resolved = shutil.which(name)
    if resolved:
        return resolved
    raise SystemExit(
        f"Required tool '{name}' was not found in PATH. "
        f"Install Node.js/npm and reopen the launcher."
    )


def _build_frontend_bundle(env: dict[str, str]) -> tuple[bool, str]:
    cmd = [choose_tool("npm"), "run", "build"]
    proc = subprocess.run(
        cmd,
        cwd=FRONTEND_DIR,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=False,
    )
    if proc.returncode == 0:
        return True, ""
    tail = "\n".join((proc.stdout or "").splitlines()[-8:] + (proc.stderr or "").splitlines()[-8:]).strip()
    reason = tail if tail else f"npm build exited with code {proc.returncode}"
    return False, reason


def _start_frontend_static_server(
    args: argparse.Namespace,
    env: dict[str, str],
    creationflags: int,
) -> tuple[subprocess.Popen | None, str]:
    dist_dir = FRONTEND_DIR / "dist"
    if not dist_dir.exists():
        ok, reason = _build_frontend_bundle(env)
        if not ok:
            return None, f"static fallback build failed: {reason}"
    cmd = [
        choose_backend_python(),
        "-m",
        "http.server",
        str(args.frontend_port),
        "--bind",
        args.host,
    ]
    try:
        proc = subprocess.Popen(
            cmd,
            cwd=dist_dir,
            env=env,
            creationflags=creationflags,
        )
    except Exception as exc:
        return None, f"static fallback launch failed: {exc}"
    return proc, ""


def choose_electron() -> str:
    if os.name == "nt":
        local_electron = REPO_ROOT / "node_modules" / ".bin" / "electron.cmd"
        if local_electron.exists():
            return str(local_electron)
    local_js = REPO_ROOT / "node_modules" / "electron" / "cli.js"
    if local_js.exists():
        return f"{sys.executable} {str(local_js)}"
    raise SystemExit(
        "Electron was not found in this repo. Run 'npm install' in repo root first."
    )


def choose_n8n_command(args: argparse.Namespace) -> list[str]:
    custom = str(getattr(args, "n8n_command", "") or "").strip()
    if custom:
        return shlex.split(custom, posix=(os.name != "nt"))

    local_bin = (
        REPO_ROOT
        / "data"
        / "agent_space"
        / "tools"
        / "n8n"
        / "node_modules"
        / ".bin"
        / ("n8n.cmd" if os.name == "nt" else "n8n")
    )
    if local_bin.exists():
        return [str(local_bin), "start", "--port", str(args.n8n_port)]

    if os.name == "nt":
        global_n8n = shutil.which("n8n.cmd")
        if global_n8n:
            return [global_n8n, "start", "--port", str(args.n8n_port)]
        npx_bin = shutil.which("npx.cmd")
        if npx_bin:
            return [npx_bin, "n8n", "start", "--port", str(args.n8n_port)]
    else:
        global_n8n = shutil.which("n8n")
        if global_n8n:
            return [global_n8n, "start", "--port", str(args.n8n_port)]
        npx_bin = shutil.which("npx")
        if npx_bin:
            return [npx_bin, "n8n", "start", "--port", str(args.n8n_port)]

    raise SystemExit(
        "n8n executable was not found. Install n8n (npm install -g n8n) "
        "or run from the Automation tab with Install Local n8n."
    )


def start_services(args: argparse.Namespace) -> None:
    pids = load_pids()
    backend_pid = int(pids.get("backend_pid", 0) or 0)
    frontend_pid = int(pids.get("frontend_pid", 0) or 0)
    n8n_pid = int(pids.get("n8n_pid", 0) or 0)
    with_n8n = bool(getattr(args, "with_n8n", False))
    if backend_pid and is_running(backend_pid):
        print(f"Backend already running (PID {backend_pid}).")
    if frontend_pid and is_running(frontend_pid):
        print(f"Frontend already running (PID {frontend_pid}).")
    if with_n8n and n8n_pid and is_running(n8n_pid):
        print(f"n8n already running (PID {n8n_pid}).")
    if (
        backend_pid
        and is_running(backend_pid)
        and frontend_pid
        and is_running(frontend_pid)
        and (not with_n8n or (n8n_pid and is_running(n8n_pid)))
    ):
        if args.open:
            open_ui(args)
        return

    env = os.environ.copy()
    env["BACKEND_PORT"] = str(args.backend_port)
    env["FRONTEND_PORT"] = str(args.frontend_port)
    env["AGENT_SPACE_MODEL"] = args.model
    env["AGENT_SPACE_COMMAND_PROFILE"] = args.command_profile
    env["AGENT_SPACE_REVIEW_GATE"] = "true" if args.review_gate else "false"
    env["AGENT_SPACE_ALLOW_SHELL"] = "true" if args.allow_shell else "false"
    env["AGENT_SPACE_MAX_ACTIONS"] = str(args.max_actions)
    env["AGENT_SPACE_MAX_SECONDS"] = str(args.max_seconds)
    env["AGENT_SPACE_DESKTOP_MODE"] = "true" if args.desktop_mode else "false"
    env["AGENT_SPACE_DATA_ROOT"] = str(REPO_ROOT / "data" / "agent_space")
    env["AGENT_SPACE_GIT_CHECKPOINT"] = "true" if args.create_git_checkpoint else "false"
    env["AGENT_SPACE_PROACTIVE_ENABLED"] = "true" if args.proactive_enabled else "false"
    env["AGENT_SPACE_PROACTIVE_TICK_SECONDS"] = str(args.proactive_tick_seconds)
    env["AGENT_SPACE_N8N_ENABLED"] = "true"
    env["AGENT_SPACE_N8N_MODE"] = "managed" if with_n8n else "external"
    env["AGENT_SPACE_N8N_PORT"] = str(args.n8n_port)
    env["AGENT_SPACE_N8N_URL"] = args.n8n_url or f"http://localhost:{args.n8n_port}"
    env["AGENT_SPACE_N8N_AUTO_START"] = "true" if bool(getattr(args, "n8n_auto_start", False)) else "false"

    backend_cmd = [
        choose_backend_python(),
        "-m",
        "uvicorn",
        "main:app",
        "--host",
        args.host,
        "--port",
        str(args.backend_port),
    ]
    frontend_cmd = [
        choose_tool("npm"),
        "run",
        "dev",
        "--",
        "--host",
        args.host,
        "--port",
        str(args.frontend_port),
    ]

    creationflags = 0
    if os.name == "nt":
        creationflags = subprocess.CREATE_NEW_PROCESS_GROUP  # type: ignore[attr-defined]

    backend_proc = subprocess.Popen(
        backend_cmd,
        cwd=BACKEND_DIR,
        env=env,
        creationflags=creationflags,
    )
    try:
        time.sleep(1)
        frontend_proc = subprocess.Popen(
            frontend_cmd,
            cwd=FRONTEND_DIR,
            env=env,
            creationflags=creationflags,
        )
    except Exception:
        terminate_pid(backend_proc.pid)
        raise

    n8n_proc: subprocess.Popen | None = None
    if with_n8n and not (n8n_pid and is_running(n8n_pid)):
        n8n_cmd = choose_n8n_command(args)
        try:
            n8n_proc = subprocess.Popen(
                n8n_cmd,
                cwd=REPO_ROOT,
                env=env,
                creationflags=creationflags,
            )
        except Exception:
            # n8n is optional for service launch; keep backend/frontend alive.
            n8n_proc = None

    frontend_mode = "dev-vite"
    frontend_fallback_note = ""
    backend_ok, backend_msg = _wait_for_tcp_ready(
        "backend",
        host=args.host,
        port=int(args.backend_port),
        timeout_seconds=20,
        proc=backend_proc,
    )
    frontend_ok, frontend_msg = _wait_for_tcp_ready(
        "frontend",
        host=args.host,
        port=int(args.frontend_port),
        timeout_seconds=25,
        proc=frontend_proc,
    )
    if not frontend_ok:
        terminate_pid(frontend_proc.pid)
        fallback_proc, fallback_err = _start_frontend_static_server(args, env, creationflags)
        if fallback_proc is not None:
            frontend_proc = fallback_proc
            frontend_mode = "prod-static"
            frontend_fallback_note = "Frontend dev failed; using static bundle fallback."
            frontend_ok, frontend_msg = _wait_for_tcp_ready(
                "frontend-static",
                host=args.host,
                port=int(args.frontend_port),
                timeout_seconds=20,
                proc=frontend_proc,
            )
        elif fallback_err:
            frontend_msg = f"{frontend_msg} {fallback_err}".strip()
    if not backend_ok or not frontend_ok:
        terminate_pid(frontend_proc.pid)
        terminate_pid(backend_proc.pid)
        if n8n_proc is not None:
            terminate_pid(n8n_proc.pid)
        failures = [msg for msg in (backend_msg, frontend_msg) if msg]
        detail = " ".join(failures).strip() or "Startup health checks failed."
        raise SystemExit(f"Service startup failed. {detail}")

    # Guard against false positives when requested ports are occupied by other
    # processes and child processes exit immediately after spawn.
    time.sleep(1.0)
    exited_msgs: list[str] = []
    if backend_proc.poll() is not None:
        exited_msgs.append(f"backend exited early (code {backend_proc.returncode})")
    if frontend_proc.poll() is not None:
        exited_msgs.append(f"frontend exited early (code {frontend_proc.returncode})")
    if exited_msgs:
        terminate_pid(frontend_proc.pid)
        terminate_pid(backend_proc.pid)
        if n8n_proc is not None:
            terminate_pid(n8n_proc.pid)
        hint = "requested ports may already be in use."
        raise SystemExit(f"Service startup failed. {'; '.join(exited_msgs)} ({hint})")

    data = {
        "backend_pid": backend_proc.pid,
        "frontend_pid": frontend_proc.pid,
        "n8n_pid": int(n8n_proc.pid) if n8n_proc else (n8n_pid if n8n_pid and is_running(n8n_pid) else 0),
        "backend_port": args.backend_port,
        "frontend_port": args.frontend_port,
        "n8n_port": args.n8n_port,
        "frontend_mode": frontend_mode,
        "started_at": time.time(),
    }
    save_pids(data)
    print(f"Backend started (PID {backend_proc.pid}) on http://localhost:{args.backend_port}")
    print(f"Frontend started (PID {frontend_proc.pid}) on http://localhost:{args.frontend_port} [{frontend_mode}]")
    if frontend_fallback_note:
        print(frontend_fallback_note)
    if n8n_proc:
        print(f"n8n started (PID {n8n_proc.pid}) on http://localhost:{args.n8n_port}")
    elif with_n8n:
        print(f"n8n requested. If not running, open Automation tab to install/start local n8n on port {args.n8n_port}.")
    if bool(getattr(args, "open", False)):
        open_ui(args)


def stop_services(_: argparse.Namespace) -> None:
    pids = load_pids()
    stopped_any = False
    for key in ("frontend_pid", "backend_pid", "desktop_pid", "n8n_pid"):
        pid = int(pids.get(key, 0) or 0)
        if pid and terminate_pid(pid):
            print(f"Stopped {key} ({pid}).")
            stopped_any = True
    if not stopped_any:
        print("No recorded Agent Space processes were running.")
    if PID_FILE.exists():
        PID_FILE.unlink()


def open_ui(args: argparse.Namespace) -> None:
    url = f"http://localhost:{args.frontend_port}"
    _open_url(url)
    print(f"Opened {url}")


def start_desktop(args: argparse.Namespace) -> None:
    if args.with_services:
        start_services(args)

    if not DESKTOP_MAIN.exists():
        raise SystemExit(f"Desktop entry not found: {DESKTOP_MAIN}")

    env = os.environ.copy()
    env["AGENTSPACE_UI_URL"] = f"http://localhost:{args.frontend_port}"
    electron_bin = choose_electron()
    if " " in electron_bin and electron_bin.endswith("cli.js"):
        # Fallback path for non-Windows environments with JS entrypoint.
        electron_cmd = electron_bin.split(" ", 1) + [str(DESKTOP_MAIN)]
    else:
        electron_cmd = [electron_bin, str(DESKTOP_MAIN)]
    creationflags = 0
    if os.name == "nt":
        creationflags = subprocess.CREATE_NEW_PROCESS_GROUP  # type: ignore[attr-defined]
    proc = subprocess.Popen(electron_cmd, cwd=REPO_ROOT, env=env, creationflags=creationflags)
    time.sleep(0.8)
    if proc.poll() is not None:
        raise SystemExit(f"Desktop app failed to start (exit code {proc.returncode}).")

    pids = load_pids()
    pids["desktop_pid"] = proc.pid
    pids["frontend_port"] = args.frontend_port
    pids["backend_port"] = args.backend_port
    save_pids(pids)
    print(f"Desktop app started (PID {proc.pid}).")


def create_shortcuts(_: argparse.Namespace) -> None:
    desktop = Path.home() / "Desktop"
    output_dir = desktop
    try:
        output_dir.mkdir(parents=True, exist_ok=True)
    except Exception:
        output_dir = REPO_ROOT / "data" / "agent_space" / "runtime" / "desktop_shortcuts"
        output_dir.mkdir(parents=True, exist_ok=True)
    commands = {
        "Agent Space - Start.cmd": _lifecycle_cmd("start --open"),
        "Agent Space - Start + n8n.cmd": _lifecycle_cmd("start --open --with-n8n"),
        "Agent Space - Stop.cmd": _lifecycle_cmd("stop"),
        "Agent Space - Open UI.cmd": _lifecycle_cmd("open-ui"),
        "Agent Space - Desktop.cmd": _lifecycle_cmd("desktop --with-services"),
        "Agent Space - Shortcuts.cmd": _lifecycle_cmd("shortcuts"),
        "jimAI - Free Stack Setup.cmd": _lifecycle_cmd("free-stack-setup --start --open --shortcuts"),
        "jimAI - Install Podman Runtime.cmd": _lifecycle_cmd("free-stack-install-runtime --runtime podman"),
        "jimAI - Install Docker Runtime.cmd": _lifecycle_cmd("free-stack-install-runtime --runtime docker"),
        "jimAI - Free Stack Start.cmd": _lifecycle_cmd("free-stack-start --open"),
        "jimAI - Free Stack Stop.cmd": _lifecycle_cmd("free-stack-stop"),
        "jimAI - Free Stack Open Dashboards.cmd": _lifecycle_cmd("free-stack-open"),
    }
    for filename, command in commands.items():
        content = f"@echo off\r\ncd /d \"{REPO_ROOT}\"\r\n{command}\r\n"
        try:
            (output_dir / filename).write_text(content, encoding="utf-8")
        except PermissionError:
            fallback = REPO_ROOT / "data" / "agent_space" / "runtime" / "desktop_shortcuts"
            fallback.mkdir(parents=True, exist_ok=True)
            (fallback / filename).write_text(content, encoding="utf-8")
            output_dir = fallback
    print(f"Created {len(commands)} desktop shortcuts in {output_dir}")


def free_stack_setup(args: argparse.Namespace) -> None:
    if not FREE_STACK_COMPOSE.exists():
        raise SystemExit(f"Free stack compose file not found: {FREE_STACK_COMPOSE}")

    env_map = _ensure_free_stack_env(force_rotate_passwords=bool(getattr(args, "rotate_passwords", False)))
    if bool(getattr(args, "shortcuts", False)):
        _create_free_stack_shortcuts(env_map)

    should_pull = bool(getattr(args, "pull", True))
    should_start = bool(getattr(args, "start", False))
    if should_pull or should_start:
        compose = _detect_compose_base()
        print(f"Using compose runtime: {' '.join(compose)}")

        if should_pull:
            pull = _run_compose(compose, ["pull"], env_file=FREE_STACK_ENV_FILE)
            if pull.returncode != 0:
                raise SystemExit("Failed to download free stack images. Check container runtime and internet access.")

        if should_start:
            up = _run_compose(compose, ["up", "-d"], env_file=FREE_STACK_ENV_FILE)
            if up.returncode != 0:
                raise SystemExit("Failed to start free stack containers.")

    _print_free_stack_credential_summary(env_map)
    if bool(getattr(args, "open", False)):
        _open_free_stack_urls(env_map)


def free_stack_start(args: argparse.Namespace) -> None:
    env_map = _ensure_free_stack_env(force_rotate_passwords=False)
    compose = _detect_compose_base()
    up = _run_compose(compose, ["up", "-d"], env_file=FREE_STACK_ENV_FILE)
    if up.returncode != 0:
        raise SystemExit("Failed to start free stack containers.")
    print("Free stack containers started.")
    _print_free_stack_credential_summary(env_map)
    if bool(getattr(args, "open", False)):
        _open_free_stack_urls(env_map)


def free_stack_stop(_: argparse.Namespace) -> None:
    compose = _detect_compose_base()
    down = _run_compose(compose, ["down"], env_file=FREE_STACK_ENV_FILE)
    if down.returncode != 0:
        raise SystemExit("Failed to stop free stack containers.")
    print("Free stack containers stopped.")


def free_stack_open(_: argparse.Namespace) -> None:
    env_map = _ensure_free_stack_env(force_rotate_passwords=False)
    _open_free_stack_urls(env_map)
    _print_free_stack_credential_summary(env_map)


def free_stack_status(_: argparse.Namespace) -> None:
    compose = _detect_compose_base()
    ps = _run_compose(compose, ["ps"], env_file=FREE_STACK_ENV_FILE)
    if ps.returncode != 0:
        raise SystemExit("Failed to read free stack status.")


def free_stack_install_runtime(args: argparse.Namespace) -> None:
    runtime = str(getattr(args, "runtime", "podman")).strip().lower()
    winget = shutil.which("winget")
    if not winget:
        raise SystemExit(
            "winget is not available on this machine. Install Docker/Podman manually and rerun free-stack setup."
        )

    package_id = "RedHat.Podman-Desktop" if runtime == "podman" else "Docker.DockerDesktop"
    cmd = [
        winget,
        "install",
        "--id",
        package_id,
        "-e",
        "--accept-package-agreements",
        "--accept-source-agreements",
    ]
    print(f"Installing runtime via winget: {package_id}")
    result = subprocess.run(cmd, cwd=REPO_ROOT, text=True, check=False)
    if result.returncode != 0:
        raise SystemExit(f"Runtime install command failed for {package_id}.")
    print(f"Runtime install command completed for {package_id}.")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Agent Space lifecycle utility.")
    parser.add_argument("--host", default="0.0.0.0")
    parser.add_argument("--backend-port", type=int, default=8000)
    parser.add_argument("--frontend-port", type=int, default=5173)
    parser.add_argument("--model", default="qwen2.5-coder:14b")
    parser.add_argument("--command-profile", default="safe", choices=["safe", "dev", "unrestricted"])
    parser.add_argument("--review-gate", dest="review_gate", action="store_true", default=True)
    parser.add_argument("--no-review-gate", dest="review_gate", action="store_false")
    parser.add_argument("--allow-shell", action="store_true", default=False)
    parser.add_argument("--max-actions", type=int, default=40)
    parser.add_argument("--max-seconds", type=int, default=1200)
    parser.add_argument("--desktop-mode", action="store_true", default=False)
    parser.add_argument("--create-git-checkpoint", action="store_true", default=False)
    parser.add_argument("--proactive-enabled", action="store_true", default=False)
    parser.add_argument("--proactive-tick-seconds", type=int, default=5)
    parser.add_argument("--n8n-port", type=int, default=5678)
    parser.add_argument("--n8n-url", default="")
    parser.add_argument("--n8n-command", default="")
    parser.add_argument("--n8n-auto-start", action="store_true", default=False)

    sub = parser.add_subparsers(dest="command", required=True)
    start = sub.add_parser("start", help="Start backend + frontend.")
    start.add_argument("--open", action="store_true", default=False)
    start.add_argument("--with-n8n", action="store_true", default=False)

    sub.add_parser("stop", help="Stop recorded Agent Space processes.")
    sub.add_parser("open-ui", help="Open UI in browser.")
    desktop = sub.add_parser("desktop", help="Start desktop app shell.")
    desktop.add_argument("--with-services", action="store_true", default=False)
    desktop.add_argument("--with-n8n", action="store_true", default=False)
    sub.add_parser("shortcuts", help="Create desktop shortcut .cmd files.")

    free_setup = sub.add_parser(
        "free-stack-setup",
        help="Download and configure free local stack services with local accounts.",
    )
    free_setup.add_argument("--start", action="store_true", default=True)
    free_setup.add_argument("--no-start", dest="start", action="store_false")
    free_setup.add_argument("--pull", action="store_true", default=True)
    free_setup.add_argument("--no-pull", dest="pull", action="store_false")
    free_setup.add_argument("--open", action="store_true", default=False)
    free_setup.add_argument("--shortcuts", action="store_true", default=True)
    free_setup.add_argument("--no-shortcuts", dest="shortcuts", action="store_false")
    free_setup.add_argument("--rotate-passwords", action="store_true", default=False)

    free_start = sub.add_parser("free-stack-start", help="Start free local stack containers.")
    free_start.add_argument("--open", action="store_true", default=False)
    sub.add_parser("free-stack-stop", help="Stop free local stack containers.")
    sub.add_parser("free-stack-open", help="Open free stack dashboards in browser.")
    sub.add_parser("free-stack-status", help="Show free stack container status.")
    free_install = sub.add_parser("free-stack-install-runtime", help="Install Docker/Podman runtime via winget.")
    free_install.add_argument("--runtime", choices=["podman", "docker"], default="podman")
    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()
    ensure_runtime_dir()

    if args.command == "start":
        start_services(args)
    elif args.command == "stop":
        stop_services(args)
    elif args.command == "open-ui":
        open_ui(args)
    elif args.command == "desktop":
        start_desktop(args)
    elif args.command == "shortcuts":
        create_shortcuts(args)
    elif args.command == "free-stack-setup":
        free_stack_setup(args)
    elif args.command == "free-stack-start":
        free_stack_start(args)
    elif args.command == "free-stack-stop":
        free_stack_stop(args)
    elif args.command == "free-stack-open":
        free_stack_open(args)
    elif args.command == "free-stack-status":
        free_stack_status(args)
    elif args.command == "free-stack-install-runtime":
        free_stack_install_runtime(args)
    else:
        parser.error(f"Unknown command: {args.command}")


if __name__ == "__main__":
    main()
