"""Lifecycle utility for Agent Space.

Commands:
- start backend + frontend
- stop backend/frontend
- open UI in browser
- start desktop app shell
- create desktop shortcuts
"""

from __future__ import annotations

import argparse
import json
import os
import secrets
import shlex
import signal
import shutil
import socket
import subprocess
import sys
import time
import urllib.error
import urllib.request
import webbrowser
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
BACKEND_DIR = REPO_ROOT / "backend"
FRONTEND_DIR = REPO_ROOT / "frontend"
FRONTEND_DEV_SCRIPT = REPO_ROOT / "scripts" / "start_frontend_dev.mjs"
FRONTEND_STATIC_SCRIPT = REPO_ROOT / "scripts" / "start_frontend_static.py"
DESKTOP_MAIN = REPO_ROOT / "desktop" / "main.cjs"
PID_FILE = REPO_ROOT / "data" / "agent_space" / "runtime" / "pids.json"
INSTANCE_STATE_FILE = PID_FILE.parent / "instances.json"
FREE_STACK_DIR = REPO_ROOT / "infra" / "free-stack"
FREE_STACK_COMPOSE = FREE_STACK_DIR / "docker-compose.yml"
SECURE_DIR = REPO_ROOT / "data" / "agent_space" / "secure"
FREE_STACK_ENV_FILE = SECURE_DIR / "free-stack.env"
FREE_STACK_CREDS_FILE = SECURE_DIR / "free-stack-credentials.txt"
FREE_STACK_ALL_SECRETS_FILE = SECURE_DIR / "all-local-secrets.txt"
LEGACY_FREE_STACK_ENV_FILE = REPO_ROOT / "data" / "agent_space" / "runtime" / "free-stack.env"
LEGACY_FREE_STACK_CREDS_FILE = REPO_ROOT / "data" / "agent_space" / "runtime" / "free-stack-credentials.txt"
FREE_STACK_PROJECT = "jimai-free"

FREE_STACK_DEFAULTS = {
    "POSTGRES_DB": "agentspace",
    "POSTGRES_USER": "agentspace",
    "POSTGRES_PASSWORD": "",
    "POSTGRES_PORT": "15432",
    "PGADMIN_DEFAULT_EMAIL": "admin@jimai.app",
    "PGADMIN_DEFAULT_PASSWORD": "",
    "PGADMIN_PORT": "15050",
    "REDIS_PASSWORD": "",
    "REDIS_PORT": "16379",
    "REDIS_COMMANDER_USER": "admin",
    "REDIS_COMMANDER_PASSWORD": "",
    "REDIS_COMMANDER_PORT": "18081",
    "MINIO_ROOT_USER": "minioadmin",
    "MINIO_ROOT_PASSWORD": "",
    "MINIO_API_PORT": "19000",
    "MINIO_CONSOLE_PORT": "19001",
    "GRAFANA_ADMIN_USER": "admin",
    "GRAFANA_ADMIN_PASSWORD": "",
    "GRAFANA_PORT": "13000",
    "PROMETHEUS_PORT": "19090",
    "LOKI_PORT": "13100",
    "QDRANT_PORT": "16333",
    "QDRANT_API_KEY": "",
    "SEARXNG_PORT": "18082",
    "GOTIFY_DEFAULTUSER_NAME": "admin",
    "GOTIFY_DEFAULTUSER_PASS": "",
    "GOTIFY_PORT": "18080",
}


def ensure_runtime_dir() -> None:
    PID_FILE.parent.mkdir(parents=True, exist_ok=True)
    ensure_secure_dir()


def ensure_secure_dir() -> None:
    SECURE_DIR.mkdir(parents=True, exist_ok=True)


def _restrict_file_permissions(path: Path) -> None:
    # Best-effort local hardening. On Windows, chmod is limited but still reduces accidental access.
    try:
        os.chmod(path, 0o600)
    except OSError:
        pass


def _cleanup_legacy_secret_files() -> None:
    for old_path in (LEGACY_FREE_STACK_ENV_FILE, LEGACY_FREE_STACK_CREDS_FILE):
        try:
            if old_path.exists():
                old_path.unlink()
        except OSError:
            pass


def _random_secret(length: int = 26) -> str:
    raw = secrets.token_urlsafe(max(20, length))
    return raw[:length]


def _parse_env_file(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    data: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        data[key.strip()] = value.strip()
    return data


def _write_env_file(path: Path, env_map: dict[str, str]) -> None:
    lines = ["# Auto-generated by scripts/agentspace_lifecycle.py"]
    for key in sorted(env_map.keys()):
        lines.append(f"{key}={env_map[key]}")
    ensure_secure_dir()
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    _restrict_file_permissions(path)


def _ensure_free_stack_env(force_rotate_passwords: bool = False) -> dict[str, str]:
    current = _parse_env_file(FREE_STACK_ENV_FILE)
    merged = dict(FREE_STACK_DEFAULTS)
    merged.update({k: v for k, v in current.items() if k in merged and str(v).strip()})
    pgadmin_email = str(merged.get("PGADMIN_DEFAULT_EMAIL", "")).strip().lower()
    if not pgadmin_email or pgadmin_email.endswith(".local"):
        merged["PGADMIN_DEFAULT_EMAIL"] = FREE_STACK_DEFAULTS["PGADMIN_DEFAULT_EMAIL"]

    secret_keys = (
        "POSTGRES_PASSWORD",
        "PGADMIN_DEFAULT_PASSWORD",
        "REDIS_PASSWORD",
        "REDIS_COMMANDER_PASSWORD",
        "MINIO_ROOT_PASSWORD",
        "GRAFANA_ADMIN_PASSWORD",
        "QDRANT_API_KEY",
        "GOTIFY_DEFAULTUSER_PASS",
    )
    for key in secret_keys:
        if force_rotate_passwords or not str(merged.get(key, "")).strip():
            merged[key] = _random_secret()

    _write_env_file(FREE_STACK_ENV_FILE, merged)
    _write_free_stack_credentials(merged)
    _write_all_local_secrets(merged)
    _cleanup_legacy_secret_files()
    return merged


def _write_free_stack_credentials(env_map: dict[str, str]) -> None:
    lines = [
        "jimAI Free Local Stack Credentials",
        f"Generated: {time.strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "Use these URLs in your browser and sign in with credentials below.",
        "",
        f"Grafana: http://localhost:{env_map['GRAFANA_PORT']}",
        f"  username: {env_map['GRAFANA_ADMIN_USER']}",
        f"  password: {env_map['GRAFANA_ADMIN_PASSWORD']}",
        "",
        f"MinIO Console: http://localhost:{env_map['MINIO_CONSOLE_PORT']}",
        f"  username: {env_map['MINIO_ROOT_USER']}",
        f"  password: {env_map['MINIO_ROOT_PASSWORD']}",
        "",
        f"pgAdmin: http://localhost:{env_map['PGADMIN_PORT']}",
        f"  email: {env_map['PGADMIN_DEFAULT_EMAIL']}",
        f"  password: {env_map['PGADMIN_DEFAULT_PASSWORD']}",
        "",
        f"Redis Commander: http://localhost:{env_map['REDIS_COMMANDER_PORT']}",
        f"  username: {env_map['REDIS_COMMANDER_USER']}",
        f"  password: {env_map['REDIS_COMMANDER_PASSWORD']}",
        "",
        f"Gotify: http://localhost:{env_map['GOTIFY_PORT']}",
        f"  username: {env_map['GOTIFY_DEFAULTUSER_NAME']}",
        f"  password: {env_map['GOTIFY_DEFAULTUSER_PASS']}",
        "",
        f"Qdrant Dashboard: http://localhost:{env_map['QDRANT_PORT']}/dashboard",
        f"  api key: {env_map['QDRANT_API_KEY']}",
        "",
        f"SearXNG: http://localhost:{env_map['SEARXNG_PORT']}",
        "  no login required (local meta-search endpoint)",
        "",
        "Infra ports:",
        f"  Postgres: localhost:{env_map['POSTGRES_PORT']}",
        f"  Redis: localhost:{env_map['REDIS_PORT']}",
        f"  MinIO API: localhost:{env_map['MINIO_API_PORT']}",
        f"  Prometheus: localhost:{env_map['PROMETHEUS_PORT']}",
        f"  Loki: localhost:{env_map['LOKI_PORT']}",
    ]
    ensure_secure_dir()
    FREE_STACK_CREDS_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    _restrict_file_permissions(FREE_STACK_CREDS_FILE)


def _write_all_local_secrets(env_map: dict[str, str]) -> None:
    lines = [
        "jimAI Local Secrets Bundle",
        f"Generated: {time.strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "This file centralizes all generated local credentials and secret env values.",
        "",
        f"Credentials file: {FREE_STACK_CREDS_FILE}",
        "",
        "[ENV]",
    ]
    for key in sorted(env_map.keys()):
        lines.append(f"{key}={env_map[key]}")
    ensure_secure_dir()
    FREE_STACK_ALL_SECRETS_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    _restrict_file_permissions(FREE_STACK_ALL_SECRETS_FILE)


def _detect_compose_base() -> list[str]:
    candidates: list[list[str]] = [
        ["docker", "compose"],
        ["docker-compose"],
        ["podman", "compose"],
        ["podman-compose"],
    ]
    for base in candidates:
        try:
            probe = subprocess.run(
                [*base, "version"],
                cwd=REPO_ROOT,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                timeout=20,
                check=False,
            )
        except (OSError, FileNotFoundError, subprocess.TimeoutExpired):
            continue
        if probe.returncode == 0:
            return base
    raise SystemExit(
        "No supported container compose runtime found.\n"
        "Install one of: Docker (with compose plugin), docker-compose, Podman (compose), or podman-compose.\n"
        "Windows examples:\n"
        "  winget install Docker.DockerDesktop\n"
        "  winget install RedHat.Podman-Desktop"
    )


def _run_compose(base: list[str], compose_args: list[str], *, env_file: Path) -> subprocess.CompletedProcess:
    cmd = [*base, "--env-file", str(env_file), "-f", str(FREE_STACK_COMPOSE), "-p", FREE_STACK_PROJECT, *compose_args]
    compose_env = os.environ.copy()
    compose_env.update(_parse_env_file(env_file))
    return subprocess.run(cmd, cwd=REPO_ROOT, env=compose_env, text=True, check=False)


def _open_url(url: str) -> None:
    if os.name == "nt":
        try:
            os.startfile(url)  # type: ignore[attr-defined]
            return
        except OSError:
            pass
    webbrowser.open(url)


def _shortcut_python_executable() -> str:
    venv_python = REPO_ROOT / "backend" / ".venv" / "Scripts" / "python.exe"
    if venv_python.exists():
        return r"backend\.venv\Scripts\python.exe"
    return "python"


def _lifecycle_cmd(args: str) -> str:
    python_bin = _shortcut_python_executable()
    if args.strip():
        return f"\"{python_bin}\" scripts\\agentspace_lifecycle.py {args}"
    return f"\"{python_bin}\" scripts\\agentspace_lifecycle.py"


def _cmd_shortcut_body(inner_command: str) -> str:
    """Batch file content that pauses on error so Explorer double-clicks show failures."""
    line = inner_command.strip().replace("\n", "\r\n")
    return (
        "@echo off\r\n"
        f'cd /d "{REPO_ROOT}"\r\n'
        f"{line}\r\n"
        "if errorlevel 1 (\r\n"
        "  echo.\r\n"
        "  echo JimAI reported an error. Read the messages above, then press any key to close.\r\n"
        "  pause\r\n"
        "  exit /b 1\r\n"
        ")\r\n"
    )


def _open_free_stack_urls(env_map: dict[str, str]) -> None:
    urls = [
        f"http://localhost:{env_map['GRAFANA_PORT']}",
        f"http://localhost:{env_map['MINIO_CONSOLE_PORT']}",
        f"http://localhost:{env_map['PGADMIN_PORT']}",
        f"http://localhost:{env_map['REDIS_COMMANDER_PORT']}",
        f"http://localhost:{env_map['GOTIFY_PORT']}",
        f"http://localhost:{env_map['QDRANT_PORT']}/dashboard",
        f"http://localhost:{env_map['SEARXNG_PORT']}",
    ]
    for url in urls:
        _open_url(url)
    print("Opened free stack dashboards in browser.")


def _create_free_stack_shortcuts(env_map: dict[str, str]) -> None:
    desktop = Path.home() / "Desktop"
    output_dir = desktop
    try:
        output_dir.mkdir(parents=True, exist_ok=True)
    except Exception:
        output_dir = REPO_ROOT / "data" / "agent_space" / "runtime" / "desktop_shortcuts"
        output_dir.mkdir(parents=True, exist_ok=True)
    commands = {
        "jimAI - Free Stack Setup.cmd": _lifecycle_cmd("free-stack-setup --start --open --shortcuts"),
        "jimAI - Install Podman Runtime.cmd": _lifecycle_cmd("free-stack-install-runtime --runtime podman"),
        "jimAI - Install Docker Runtime.cmd": _lifecycle_cmd("free-stack-install-runtime --runtime docker"),
        "jimAI - Free Stack Start.cmd": _lifecycle_cmd("free-stack-start --open"),
        "jimAI - Free Stack Stop.cmd": _lifecycle_cmd("free-stack-stop"),
        "jimAI - Free Stack Open Dashboards.cmd": _lifecycle_cmd("free-stack-open"),
        "jimAI - Launch Desktop + Free Stack.cmd": f"{_lifecycle_cmd('free-stack-start')} && {_lifecycle_cmd('desktop --with-services')}",
    }
    for filename, command in commands.items():
        content = _cmd_shortcut_body(command)
        try:
            (output_dir / filename).write_text(content, encoding="utf-8")
        except PermissionError:
            fallback = REPO_ROOT / "data" / "agent_space" / "runtime" / "desktop_shortcuts"
            fallback.mkdir(parents=True, exist_ok=True)
            (fallback / filename).write_text(content, encoding="utf-8")
            output_dir = fallback

    desktop_creds = output_dir / "jimAI - Free Stack Credentials.txt"
    lines = [
        "jimAI Free Stack Login Shortcuts",
        "",
        f"Grafana: http://localhost:{env_map['GRAFANA_PORT']}",
        f"MinIO Console: http://localhost:{env_map['MINIO_CONSOLE_PORT']}",
        f"pgAdmin: http://localhost:{env_map['PGADMIN_PORT']}",
        f"Redis Commander: http://localhost:{env_map['REDIS_COMMANDER_PORT']}",
        f"Gotify: http://localhost:{env_map['GOTIFY_PORT']}",
        f"Qdrant Dashboard: http://localhost:{env_map['QDRANT_PORT']}/dashboard",
        f"SearXNG: http://localhost:{env_map['SEARXNG_PORT']}",
        "",
        f"Credentials source: {FREE_STACK_CREDS_FILE}",
    ]
    desktop_creds.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Created free stack desktop launchers in {output_dir}")


def _print_free_stack_credential_summary(env_map: dict[str, str]) -> None:
    print("Free stack is configured with local accounts:")
    print(f"  Grafana:         http://localhost:{env_map['GRAFANA_PORT']}  ({env_map['GRAFANA_ADMIN_USER']})")
    print(f"  MinIO Console:   http://localhost:{env_map['MINIO_CONSOLE_PORT']}  ({env_map['MINIO_ROOT_USER']})")
    print(f"  pgAdmin:         http://localhost:{env_map['PGADMIN_PORT']}  ({env_map['PGADMIN_DEFAULT_EMAIL']})")
    print(f"  Redis Commander: http://localhost:{env_map['REDIS_COMMANDER_PORT']}  ({env_map['REDIS_COMMANDER_USER']})")
    print(f"  Gotify:          http://localhost:{env_map['GOTIFY_PORT']}  ({env_map['GOTIFY_DEFAULTUSER_NAME']})")
    print(f"  Qdrant Dashboard:http://localhost:{env_map['QDRANT_PORT']}/dashboard")
    print(f"  SearXNG:         http://localhost:{env_map['SEARXNG_PORT']}")
    print(f"  Full credentials saved to: {FREE_STACK_CREDS_FILE}")
    print(f"  All secrets bundle saved to: {FREE_STACK_ALL_SECRETS_FILE}")


def load_pids() -> dict:
    if not PID_FILE.exists():
        return {}
    try:
        return json.loads(PID_FILE.read_text(encoding="utf-8"))
    except Exception:
        return {}


def save_pids(data: dict) -> None:
    ensure_runtime_dir()
    PID_FILE.write_text(json.dumps(data, indent=2), encoding="utf-8")


def load_instance_state() -> dict:
    if not INSTANCE_STATE_FILE.exists():
        return {}
    try:
        return json.loads(INSTANCE_STATE_FILE.read_text(encoding="utf-8"))
    except Exception:
        return {}


def save_instance_state(data: dict) -> None:
    ensure_runtime_dir()
    INSTANCE_STATE_FILE.write_text(json.dumps(data, indent=2), encoding="utf-8")


def load_or_create_instance_state() -> dict:
    state = load_instance_state()
    if state:
        return state
    return {
        "instances": {},
        "instance_ttl_seconds": 45,
        "stop_grace_seconds": 12,
        "pending_stop_at": None,
        "managed_ollama_pid": None,
        "last_ollama_error": "",
        "last_ollama_start_at": 0.0,
        "updated_at": time.time(),
    }


def is_running(pid: int) -> bool:
    try:
        os.kill(pid, 0)
    except OSError:
        return False
    return True


def _normalize_probe_host(host: str) -> str:
    host = str(host or "").strip()
    if host in {"", "0.0.0.0", "::"}:
        return "127.0.0.1"
    return host


def _http_probe(url: str, timeout_seconds: float = 2.5) -> tuple[bool, dict[str, object] | None]:
    try:
        with urllib.request.urlopen(url, timeout=timeout_seconds) as resp:
            status = int(getattr(resp, "status", 200) or 200)
            if status >= 500:
                return False, None
            payload = resp.read().decode("utf-8", errors="replace")
            if not payload:
                return True, None
            try:
                parsed = json.loads(payload)
            except json.JSONDecodeError:
                return True, None
            return True, parsed if isinstance(parsed, dict) else None
    except Exception:
        return False, None


def _probe_backend_health(host: str, port: int) -> tuple[bool, dict[str, object]]:
    probe_host = _normalize_probe_host(host)
    ok, payload = _http_probe(f"http://{probe_host}:{int(port)}/health")
    return ok, payload if isinstance(payload, dict) else {}


def _probe_frontend_ui(host: str, port: int) -> bool:
    probe_host = _normalize_probe_host(host)
    try:
        with urllib.request.urlopen(f"http://{probe_host}:{int(port)}/", timeout=2.5) as resp:
            status = int(getattr(resp, "status", 200) or 200)
            if status >= 500:
                return False
            body = resp.read(8192).decode("utf-8", errors="replace").lower()
    except Exception:
        return False
    return 'id="root"' in body or "loading jimai" in body or "jimai" in body


def _probe_http_service(host: str, port: int) -> bool:
    probe_host = _normalize_probe_host(host)
    ok, _ = _http_probe(f"http://{probe_host}:{int(port)}/")
    return ok


def _find_listening_pids(port: int) -> list[int]:
    target_port = str(int(port))
    pids: set[int] = set()

    if os.name == "nt":
        try:
            result = subprocess.run(
                ["netstat", "-ano", "-p", "tcp"],
                cwd=REPO_ROOT,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                timeout=10,
                check=False,
            )
        except (OSError, subprocess.TimeoutExpired):
            return []
        for raw_line in result.stdout.splitlines():
            line = raw_line.strip()
            if not line.lower().startswith("tcp"):
                continue
            parts = line.split()
            if len(parts) < 5:
                continue
            local_address = parts[1]
            state = parts[3].upper()
            pid_raw = parts[4]
            if state != "LISTENING":
                continue
            if local_address.rsplit(":", 1)[-1] != target_port:
                continue
            if pid_raw.isdigit():
                pids.add(int(pid_raw))
        return sorted(pids)

    lsof_bin = shutil.which("lsof")
    if not lsof_bin:
        return []
    try:
        result = subprocess.run(
            [lsof_bin, "-nP", f"-iTCP:{int(port)}", "-sTCP:LISTEN", "-t"],
            cwd=REPO_ROOT,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=10,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return []
    for raw_line in result.stdout.splitlines():
        pid_raw = raw_line.strip()
        if pid_raw.isdigit():
            pids.add(int(pid_raw))
    return sorted(pids)


def _first_listening_pid(port: int) -> int:
    pids = _find_listening_pids(port)
    return int(pids[0]) if pids else 0


def terminate_pid(pid: int) -> bool:
    if not pid:
        return False
    if os.name == "nt":
        try:
            result = subprocess.run(
                ["taskkill", "/PID", str(pid), "/T", "/F"],
                cwd=REPO_ROOT,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                text=True,
                timeout=15,
                check=False,
            )
            return result.returncode == 0
        except (OSError, subprocess.TimeoutExpired):
            pass
    try:
        os.kill(pid, signal.SIGTERM)
        return True
    except OSError:
        return False


def stop_managed_ollama() -> bool:
    state = load_instance_state()
    pid = int(state.get("managed_ollama_pid", 0) or 0)
    stopped = False
    if pid and terminate_pid(pid):
        print(f"Stopped managed Ollama ({pid}).")
        stopped = True
    if state:
        state["instances"] = {}
        state["pending_stop_at"] = None
        state["managed_ollama_pid"] = None
        state["updated_at"] = time.time()
        save_instance_state(state)
    return stopped


def can_reach_ollama() -> bool:
    try:
        with urllib.request.urlopen("http://127.0.0.1:11434/api/tags", timeout=2.0) as resp:
            return int(getattr(resp, "status", 200) or 200) < 500
    except Exception:
        return False


def choose_ollama() -> str | None:
    ollama_bin = shutil.which("ollama")
    if ollama_bin:
        return ollama_bin
    fallback = Path.home() / "AppData" / "Local" / "Programs" / "Ollama" / ("ollama.exe" if os.name == "nt" else "ollama")
    if fallback.exists():
        return str(fallback)
    return None


def ensure_ollama_running(timeout_seconds: float = 30.0) -> dict[str, object]:
    state = load_or_create_instance_state()
    existing_pid = int(state.get("managed_ollama_pid", 0) or 0)
    if can_reach_ollama():
        state["last_ollama_error"] = ""
        state["updated_at"] = time.time()
        save_instance_state(state)
        return {"ollama_running": True, "ollama_started": False, "managed_ollama_pid": existing_pid or None, "error": ""}

    if existing_pid and is_running(existing_pid):
        terminate_pid(existing_pid)
        state["managed_ollama_pid"] = None

    ollama_bin = choose_ollama()
    if not ollama_bin:
        error = "Ollama executable not found in PATH."
        state["last_ollama_error"] = error
        state["updated_at"] = time.time()
        save_instance_state(state)
        return {"ollama_running": False, "ollama_started": False, "managed_ollama_pid": None, "error": error}

    creationflags = 0
    if os.name == "nt":
        creationflags = subprocess.CREATE_NEW_PROCESS_GROUP  # type: ignore[attr-defined]
    try:
        proc = subprocess.Popen(
            [ollama_bin, "serve"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            creationflags=creationflags,
        )
    except Exception as exc:
        error = f"Failed to start Ollama: {exc}"
        state["last_ollama_error"] = error
        state["updated_at"] = time.time()
        save_instance_state(state)
        return {"ollama_running": False, "ollama_started": False, "managed_ollama_pid": None, "error": error}

    deadline = time.time() + max(5.0, float(timeout_seconds))
    while time.time() < deadline:
        if can_reach_ollama():
            state["managed_ollama_pid"] = int(proc.pid)
            state["last_ollama_error"] = ""
            state["last_ollama_start_at"] = time.time()
            state["updated_at"] = time.time()
            save_instance_state(state)
            return {
                "ollama_running": True,
                "ollama_started": True,
                "managed_ollama_pid": int(proc.pid),
                "error": "",
            }
        time.sleep(0.5)

    terminate_pid(int(proc.pid))
    error = "Timed out waiting for Ollama to start."
    state["managed_ollama_pid"] = None
    state["last_ollama_error"] = error
    state["updated_at"] = time.time()
    save_instance_state(state)
    return {"ollama_running": False, "ollama_started": False, "managed_ollama_pid": None, "error": error}


def _wait_for_tcp_ready(
    name: str,
    host: str,
    port: int,
    timeout_seconds: float,
    proc: subprocess.Popen | None = None,
) -> tuple[bool, str]:
    probe_host = "127.0.0.1" if host in {"0.0.0.0", "::"} else host
    deadline = time.time() + timeout_seconds
    while time.time() < deadline:
        if proc is not None and proc.poll() is not None:
            return False, f"{name} exited early (code {proc.returncode})."
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        try:
            sock.settimeout(0.4)
            if sock.connect_ex((probe_host, int(port))) == 0:
                return True, ""
        except OSError:
            pass
        finally:
            sock.close()
        time.sleep(0.2)
    return False, f"{name} did not open tcp://{probe_host}:{port} within {timeout_seconds:.0f}s."


def choose_backend_python() -> str:
    venv_python = BACKEND_DIR / ".venv" / "Scripts" / "python.exe"
    if venv_python.exists():
        return str(venv_python)
    return sys.executable


def choose_tool(name: str) -> str:
    if os.name == "nt":
        local_bin = REPO_ROOT / "node_modules" / ".bin" / f"{name}.cmd"
        if local_bin.exists():
            return str(local_bin)
    if os.name == "nt":
        win = shutil.which(f"{name}.cmd")
        if win:
            return win
    resolved = shutil.which(name)
    if resolved:
        return resolved
    raise SystemExit(
        f"Required tool '{name}' was not found in PATH. "
        f"Install Node.js/npm and reopen the launcher."
    )


def _build_frontend_bundle(env: dict[str, str]) -> tuple[bool, str]:
    cmd = [choose_tool("npm"), "run", "build"]
    proc = subprocess.run(
        cmd,
        cwd=FRONTEND_DIR,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=False,
    )
    if proc.returncode == 0:
        return True, ""
    tail = "\n".join((proc.stdout or "").splitlines()[-8:] + (proc.stderr or "").splitlines()[-8:]).strip()
    reason = tail if tail else f"npm build exited with code {proc.returncode}"
    return False, reason


def _start_frontend_static_server(
    args: argparse.Namespace,
    env: dict[str, str],
    creationflags: int,
    *,
    rebuild: bool = False,
) -> tuple[subprocess.Popen | None, str]:
    dist_dir = FRONTEND_DIR / "dist"
    if rebuild or not dist_dir.exists():
        ok, reason = _build_frontend_bundle(env)
        if not ok:
            return None, f"static fallback build failed: {reason}"
    cmd = [
        choose_backend_python(),
        str(FRONTEND_STATIC_SCRIPT),
        "--host",
        args.host,
        "--port",
        str(args.frontend_port),
    ]
    try:
        proc = subprocess.Popen(
            cmd,
            cwd=REPO_ROOT,
            env=env,
            creationflags=creationflags,
        )
    except Exception as exc:
        return None, f"static fallback launch failed: {exc}"
    return proc, ""


def choose_frontend_dev_command(args: argparse.Namespace) -> list[str]:
    if FRONTEND_DEV_SCRIPT.exists():
        return [choose_tool("node"), str(FRONTEND_DEV_SCRIPT)]
    return [
        choose_tool("npm"),
        "run",
        "dev",
        "--",
        "--host",
        args.host,
        "--port",
        str(args.frontend_port),
    ]


def choose_electron() -> str:
    if os.name == "nt":
        local_electron = REPO_ROOT / "node_modules" / ".bin" / "electron.cmd"
        if local_electron.exists():
            return str(local_electron)
    local_js = REPO_ROOT / "node_modules" / "electron" / "cli.js"
    if local_js.exists():
        return f"{sys.executable} {str(local_js)}"
    raise SystemExit(
        "Electron was not found in this repo. Run 'npm install' in repo root first."
    )


def choose_n8n_command(args: argparse.Namespace) -> list[str]:
    custom = str(getattr(args, "n8n_command", "") or "").strip()
    if custom:
        return shlex.split(custom, posix=(os.name != "nt"))

    local_bin = (
        REPO_ROOT
        / "data"
        / "agent_space"
        / "tools"
        / "n8n"
        / "node_modules"
        / ".bin"
        / ("n8n.cmd" if os.name == "nt" else "n8n")
    )
    if local_bin.exists():
        return [str(local_bin), "start", "--port", str(args.n8n_port)]

    if os.name == "nt":
        global_n8n = shutil.which("n8n.cmd")
        if global_n8n:
            return [global_n8n, "start", "--port", str(args.n8n_port)]
        npx_bin = shutil.which("npx.cmd")
        if npx_bin:
            return [npx_bin, "n8n", "start", "--port", str(args.n8n_port)]
    else:
        global_n8n = shutil.which("n8n")
        if global_n8n:
            return [global_n8n, "start", "--port", str(args.n8n_port)]
        npx_bin = shutil.which("npx")
        if npx_bin:
            return [npx_bin, "n8n", "start", "--port", str(args.n8n_port)]

    raise SystemExit(
        "n8n executable was not found. Install n8n (npm install -g n8n) "
        "or run from the Automation tab with Install Local n8n."
    )


def _backend_port_busy_message(port: int, pids: list[int]) -> str:
    pid_txt = ", ".join(str(pid) for pid in pids)
    return (
        f"Backend port {port} is already in use by PID(s) {pid_txt}, but "
        f"http://127.0.0.1:{port}/health did not respond as the JimAI backend.\n"
        "Another program may be using that port, or an old backend is stuck.\n\n"
        "Try one of these:\n"
        "  • From the JimAI repo folder run:    jimai stop\n"
        "    then start again with:             jimai\n"
        "  • Or one-shot (free port then start): jimai force\n"
        f"  • Or manually:                       taskkill /PID {pids[0]} /T /F\n"
        "  • Or with Python:\n"
        "      cd private-ai\n"
        "      backend\\.venv\\Scripts\\python.exe scripts\\agentspace_lifecycle.py "
        "desktop --with-services --free-ports\n"
    )


def start_services(args: argparse.Namespace) -> None:
    pids = load_pids()
    backend_pid = int(pids.get("backend_pid", 0) or 0)
    frontend_pid = int(pids.get("frontend_pid", 0) or 0)
    desktop_pid = int(pids.get("desktop_pid", 0) or 0)
    n8n_pid = int(pids.get("n8n_pid", 0) or 0)
    with_n8n = bool(getattr(args, "with_n8n", False))
    requested_frontend_runtime = str(getattr(args, "frontend_runtime", "static") or "static").strip().lower()
    if backend_pid and not is_running(backend_pid):
        backend_pid = 0
    if frontend_pid and not is_running(frontend_pid):
        frontend_pid = 0
    if desktop_pid and not is_running(desktop_pid):
        desktop_pid = 0
    if n8n_pid and not is_running(n8n_pid):
        n8n_pid = 0

    backend_ready, _backend_health = _probe_backend_health(args.host, args.backend_port)
    frontend_ready = _probe_frontend_ui(args.host, args.frontend_port)
    n8n_ready = bool(with_n8n and _probe_http_service(args.host, args.n8n_port))

    if not backend_ready:
        busy_backend_pids = _find_listening_pids(args.backend_port)
        if busy_backend_pids:
            deadline = time.time() + 5.0
            while time.time() < deadline and not backend_ready:
                time.sleep(0.5)
                backend_ready, _backend_health = _probe_backend_health(args.host, args.backend_port)
            if backend_ready and not backend_pid:
                backend_pid = _first_listening_pid(args.backend_port)
            elif not backend_ready:
                if busy_backend_pids and bool(getattr(args, "free_ports", False)):
                    print(
                        f"JimAI: --free-ports: stopping listener(s) on port "
                        f"{args.backend_port}: {', '.join(str(p) for p in busy_backend_pids)}"
                    )
                    for pid in busy_backend_pids:
                        terminate_pid(pid)
                    time.sleep(1.5)
                    backend_ready, _backend_health = _probe_backend_health(args.host, args.backend_port)
                    busy_backend_pids = _find_listening_pids(args.backend_port)
                if not backend_ready and busy_backend_pids:
                    raise SystemExit(_backend_port_busy_message(args.backend_port, busy_backend_pids))
                if not backend_ready and not busy_backend_pids:
                    pass

    if backend_ready and not backend_pid:
        backend_pid = _first_listening_pid(args.backend_port)
    if frontend_ready and not frontend_pid:
        frontend_pid = _first_listening_pid(args.frontend_port)
    if n8n_ready and not n8n_pid:
        n8n_pid = _first_listening_pid(args.n8n_port)

    ollama_info = ensure_ollama_running()
    ollama_error = str(ollama_info.get("error") or "").strip()
    if bool(ollama_info.get("ollama_started")):
        print(f"Ollama started (PID {int(ollama_info.get('managed_ollama_pid') or 0)}).")
    elif bool(ollama_info.get("ollama_running")):
        print("Ollama already running.")
    elif ollama_error:
        print(f"Ollama startup warning: {ollama_error}")
    if backend_pid and backend_ready:
        print(f"Backend already running (PID {backend_pid}).")
    elif backend_ready:
        print(f"Backend already available on http://localhost:{args.backend_port}.")
    if frontend_pid and frontend_ready:
        print(f"Frontend already running (PID {frontend_pid}).")
    elif frontend_ready:
        print(f"Frontend already available on http://localhost:{args.frontend_port}.")
    if with_n8n and n8n_pid and n8n_ready:
        print(f"n8n already running (PID {n8n_pid}).")
    elif with_n8n and n8n_ready:
        print(f"n8n already available on http://localhost:{args.n8n_port}.")
    if backend_ready and frontend_ready and (not with_n8n or n8n_ready):
        save_pids(
            {
                "backend_pid": backend_pid,
                "frontend_pid": frontend_pid,
                "desktop_pid": desktop_pid if desktop_pid and is_running(desktop_pid) else 0,
                "n8n_pid": n8n_pid if with_n8n else 0,
                "backend_port": args.backend_port,
                "frontend_port": args.frontend_port,
                "n8n_port": args.n8n_port,
                "frontend_mode": str(pids.get("frontend_mode") or "").strip()
                or ("prod-static" if requested_frontend_runtime == "static" else "dev-vite"),
                "started_at": float(pids.get("started_at") or time.time()),
            }
        )
        if args.open:
            open_ui(args)
        return

    env = os.environ.copy()
    env["BACKEND_PORT"] = str(args.backend_port)
    env["FRONTEND_PORT"] = str(args.frontend_port)
    env["AGENT_SPACE_MODEL"] = args.model
    env["AGENT_SPACE_COMMAND_PROFILE"] = args.command_profile
    env["AGENT_SPACE_REVIEW_GATE"] = "true" if args.review_gate else "false"
    env["AGENT_SPACE_ALLOW_SHELL"] = "true" if args.allow_shell else "false"
    env["AGENT_SPACE_MAX_ACTIONS"] = str(args.max_actions)
    env["AGENT_SPACE_MAX_SECONDS"] = str(args.max_seconds)
    env["AGENT_SPACE_DESKTOP_MODE"] = "true" if args.desktop_mode else "false"
    env["AGENT_SPACE_DATA_ROOT"] = str(REPO_ROOT / "data" / "agent_space")
    env["AGENT_SPACE_GIT_CHECKPOINT"] = "true" if args.create_git_checkpoint else "false"
    env["AGENT_SPACE_PROACTIVE_ENABLED"] = "true" if args.proactive_enabled else "false"
    env["AGENT_SPACE_PROACTIVE_TICK_SECONDS"] = str(args.proactive_tick_seconds)
    env["AGENT_SPACE_N8N_ENABLED"] = "true"
    env["AGENT_SPACE_N8N_MODE"] = "managed" if with_n8n else "external"
    env["AGENT_SPACE_N8N_PORT"] = str(args.n8n_port)
    env["AGENT_SPACE_N8N_URL"] = args.n8n_url or f"http://localhost:{args.n8n_port}"
    env["AGENT_SPACE_N8N_AUTO_START"] = "true" if bool(getattr(args, "n8n_auto_start", False)) else "false"

    backend_cmd = [
        choose_backend_python(),
        "-m",
        "uvicorn",
        "main:app",
        "--host",
        args.host,
        "--port",
        str(args.backend_port),
    ]

    creationflags = 0
    if os.name == "nt":
        creationflags = subprocess.CREATE_NEW_PROCESS_GROUP  # type: ignore[attr-defined]

    backend_proc: subprocess.Popen | None = None
    frontend_proc: subprocess.Popen | None = None
    if not backend_ready:
        backend_proc = subprocess.Popen(
            backend_cmd,
            cwd=BACKEND_DIR,
            env=env,
            creationflags=creationflags,
        )
    try:
        time.sleep(1)
        if not frontend_ready:
            if requested_frontend_runtime == "static":
                frontend_proc, frontend_err = _start_frontend_static_server(
                    args,
                    env,
                    creationflags,
                    rebuild=True,
                )
                if frontend_proc is None:
                    print(frontend_err or "Static frontend failed to start. Falling back to dev server.")
                    requested_frontend_runtime = "dev"
                    frontend_cmd = choose_frontend_dev_command(args)
                    frontend_proc = subprocess.Popen(
                        frontend_cmd,
                        cwd=FRONTEND_DIR,
                        env=env,
                        creationflags=creationflags,
                    )
            else:
                frontend_cmd = choose_frontend_dev_command(args)
                frontend_proc = subprocess.Popen(
                    frontend_cmd,
                    cwd=FRONTEND_DIR,
                    env=env,
                    creationflags=creationflags,
                )
    except Exception:
        if backend_proc is not None:
            terminate_pid(backend_proc.pid)
        raise

    n8n_proc: subprocess.Popen | None = None
    if with_n8n and not n8n_ready:
        n8n_cmd = choose_n8n_command(args)
        try:
            n8n_proc = subprocess.Popen(
                n8n_cmd,
                cwd=REPO_ROOT,
                env=env,
                creationflags=creationflags,
            )
        except Exception:
            # n8n is optional for service launch; keep backend/frontend alive.
            n8n_proc = None

    frontend_mode = str(pids.get("frontend_mode") or "").strip() or (
        "prod-static" if requested_frontend_runtime == "static" else "dev-vite"
    )
    frontend_fallback_note = ""
    if backend_proc is not None:
        backend_ok, backend_msg = _wait_for_tcp_ready(
            "backend",
            host=args.host,
            port=int(args.backend_port),
            timeout_seconds=20,
            proc=backend_proc,
        )
    else:
        backend_ok, backend_msg = True, ""
    if frontend_proc is not None:
        frontend_ok, frontend_msg = _wait_for_tcp_ready(
            "frontend",
            host=args.host,
            port=int(args.frontend_port),
            timeout_seconds=25,
            proc=frontend_proc,
        )
    else:
        frontend_ok, frontend_msg = True, ""
    if frontend_proc is not None and not frontend_ok and requested_frontend_runtime != "static":
        terminate_pid(frontend_proc.pid)
        fallback_proc, fallback_err = _start_frontend_static_server(args, env, creationflags, rebuild=True)
        if fallback_proc is not None:
            frontend_proc = fallback_proc
            frontend_mode = "prod-static"
            frontend_fallback_note = "Frontend dev failed; using static bundle fallback."
            frontend_ok, frontend_msg = _wait_for_tcp_ready(
                "frontend-static",
                host=args.host,
                port=int(args.frontend_port),
                timeout_seconds=20,
                proc=frontend_proc,
            )
        elif fallback_err:
            frontend_msg = f"{frontend_msg} {fallback_err}".strip()
    if not backend_ok or not frontend_ok:
        if frontend_proc is not None:
            terminate_pid(frontend_proc.pid)
        if backend_proc is not None:
            terminate_pid(backend_proc.pid)
        if n8n_proc is not None:
            terminate_pid(n8n_proc.pid)
        failures = [msg for msg in (backend_msg, frontend_msg) if msg]
        detail = " ".join(failures).strip() or "Startup health checks failed."
        raise SystemExit(f"Service startup failed. {detail}")

    # Guard against false positives when requested ports are occupied by other
    # processes and child processes exit immediately after spawn.
    time.sleep(1.0)
    exited_msgs: list[str] = []
    if backend_proc is not None and backend_proc.poll() is not None:
        exited_msgs.append(f"backend exited early (code {backend_proc.returncode})")
    if frontend_proc is not None and frontend_proc.poll() is not None:
        exited_msgs.append(f"frontend exited early (code {frontend_proc.returncode})")
    if exited_msgs:
        if frontend_proc is not None:
            terminate_pid(frontend_proc.pid)
        if backend_proc is not None:
            terminate_pid(backend_proc.pid)
        if n8n_proc is not None:
            terminate_pid(n8n_proc.pid)
        hint = "requested ports may already be in use."
        raise SystemExit(f"Service startup failed. {'; '.join(exited_msgs)} ({hint})")

    if backend_proc is not None:
        backend_pid = backend_proc.pid
    elif backend_ready and not backend_pid:
        backend_pid = _first_listening_pid(args.backend_port)
    if frontend_proc is not None:
        frontend_pid = frontend_proc.pid
        frontend_mode = "prod-static" if requested_frontend_runtime == "static" else "dev-vite"
    elif frontend_ready and not frontend_pid:
        frontend_pid = _first_listening_pid(args.frontend_port)
    if n8n_proc is not None:
        n8n_pid = int(n8n_proc.pid)
    elif with_n8n and n8n_ready and not n8n_pid:
        n8n_pid = _first_listening_pid(args.n8n_port)

    data = {
        "backend_pid": backend_pid,
        "frontend_pid": frontend_pid,
        "desktop_pid": desktop_pid if desktop_pid and is_running(desktop_pid) else 0,
        "n8n_pid": n8n_pid if n8n_pid and is_running(n8n_pid) else 0,
        "backend_port": args.backend_port,
        "frontend_port": args.frontend_port,
        "n8n_port": args.n8n_port,
        "frontend_mode": frontend_mode,
        "started_at": time.time(),
    }
    save_pids(data)
    if backend_proc is not None:
        print(f"Backend started (PID {backend_proc.pid}) on http://localhost:{args.backend_port}")
    elif backend_ready:
        print(f"Backend reused on http://localhost:{args.backend_port}")
    if frontend_proc is not None:
        print(f"Frontend started (PID {frontend_proc.pid}) on http://localhost:{args.frontend_port} [{frontend_mode}]")
    elif frontend_ready:
        print(f"Frontend reused on http://localhost:{args.frontend_port} [{frontend_mode}]")
    if frontend_fallback_note:
        print(frontend_fallback_note)
    if n8n_proc:
        print(f"n8n started (PID {n8n_proc.pid}) on http://localhost:{args.n8n_port}")
    elif with_n8n:
        print(f"n8n requested. If not running, open Automation tab to install/start local n8n on port {args.n8n_port}.")
    if bool(getattr(args, "open", False)):
        open_ui(args)


def stop_services(_: argparse.Namespace) -> None:
    pids = load_pids()
    stopped_any = False
    stopped_pids: set[int] = set()
    for key in ("frontend_pid", "backend_pid", "desktop_pid", "n8n_pid"):
        pid = int(pids.get(key, 0) or 0)
        if pid and terminate_pid(pid):
            print(f"Stopped {key} ({pid}).")
            stopped_any = True
            stopped_pids.add(pid)
    port_targets = {
        "frontend": int(pids.get("frontend_port", 5173) or 5173),
        "backend": int(pids.get("backend_port", 8000) or 8000),
        "n8n": int(pids.get("n8n_port", 5678) or 5678),
    }
    for label, port in port_targets.items():
        for pid in _find_listening_pids(port):
            if pid in stopped_pids:
                continue
            if terminate_pid(pid):
                print(f"Stopped {label} listener ({pid}) on port {port}.")
                stopped_any = True
                stopped_pids.add(pid)
    if stop_managed_ollama():
        stopped_any = True
    if not stopped_any:
        print("No recorded Agent Space processes were running.")
    if PID_FILE.exists():
        PID_FILE.unlink()


def open_ui(args: argparse.Namespace) -> None:
    backend_ok, _ = _probe_backend_health(args.host, args.backend_port)
    frontend_ok = _probe_frontend_ui(args.host, args.frontend_port)
    if not backend_ok or not frontend_ok:
        print("UI services are not fully running. Starting missing services first...")
        auto_args = argparse.Namespace(**vars(args))
        auto_args.open = False
        if not hasattr(auto_args, "with_n8n"):
            auto_args.with_n8n = False
        start_services(auto_args)

    url = f"http://localhost:{args.frontend_port}"
    _open_url(url)
    print(f"Opened {url}")


def start_desktop(args: argparse.Namespace) -> None:
    if args.with_services:
        start_services(args)

    if not DESKTOP_MAIN.exists():
        raise SystemExit(f"Desktop entry not found: {DESKTOP_MAIN}")

    env = os.environ.copy()
    env["AGENTSPACE_UI_URL"] = f"http://localhost:{args.frontend_port}"
    env["AGENTSPACE_AUTO_STOP"] = "1" if args.with_services else "0"
    env["AGENTSPACE_PYTHON"] = sys.executable
    env.pop("ELECTRON_RUN_AS_NODE", None)
    electron_bin = choose_electron()
    if " " in electron_bin and electron_bin.endswith("cli.js"):
        # Fallback path for non-Windows environments with JS entrypoint.
        electron_cmd = electron_bin.split(" ", 1) + [str(DESKTOP_MAIN)]
    else:
        electron_cmd = [electron_bin, str(DESKTOP_MAIN)]
    creationflags = 0
    if os.name == "nt":
        creationflags = subprocess.CREATE_NEW_PROCESS_GROUP  # type: ignore[attr-defined]
    proc = subprocess.Popen(electron_cmd, cwd=REPO_ROOT, env=env, creationflags=creationflags)
    time.sleep(0.8)
    if proc.poll() is not None:
        if proc.returncode == 0:
            print("Desktop app already running.")
            return
        raise SystemExit(f"Desktop app failed to start (exit code {proc.returncode}).")

    pids = load_pids()
    pids["desktop_pid"] = proc.pid
    pids["frontend_port"] = args.frontend_port
    pids["backend_port"] = args.backend_port
    save_pids(pids)
    print(f"Desktop app started (PID {proc.pid}).")


def create_shortcuts(_: argparse.Namespace) -> None:
    desktop = Path.home() / "Desktop"
    output_dir = desktop
    try:
        output_dir.mkdir(parents=True, exist_ok=True)
    except Exception:
        output_dir = REPO_ROOT / "data" / "agent_space" / "runtime" / "desktop_shortcuts"
        output_dir.mkdir(parents=True, exist_ok=True)
    commands = {
        "Agent Space - Start.cmd": _lifecycle_cmd("start --open"),
        "Agent Space - Start + n8n.cmd": _lifecycle_cmd("start --open --with-n8n"),
        "Agent Space - Stop.cmd": _lifecycle_cmd("stop"),
        "Agent Space - Open UI.cmd": _lifecycle_cmd("open-ui"),
        "Agent Space - Desktop.cmd": _lifecycle_cmd("desktop --with-services"),
        "Agent Space - Shortcuts.cmd": _lifecycle_cmd("shortcuts"),
        "jimAI - Free Stack Setup.cmd": _lifecycle_cmd("free-stack-setup --start --open --shortcuts"),
        "jimAI - Install Podman Runtime.cmd": _lifecycle_cmd("free-stack-install-runtime --runtime podman"),
        "jimAI - Install Docker Runtime.cmd": _lifecycle_cmd("free-stack-install-runtime --runtime docker"),
        "jimAI - Free Stack Start.cmd": _lifecycle_cmd("free-stack-start --open"),
        "jimAI - Free Stack Stop.cmd": _lifecycle_cmd("free-stack-stop"),
        "jimAI - Free Stack Open Dashboards.cmd": _lifecycle_cmd("free-stack-open"),
    }
    for filename, command in commands.items():
        content = _cmd_shortcut_body(command)
        try:
            (output_dir / filename).write_text(content, encoding="utf-8")
        except PermissionError:
            fallback = REPO_ROOT / "data" / "agent_space" / "runtime" / "desktop_shortcuts"
            fallback.mkdir(parents=True, exist_ok=True)
            (fallback / filename).write_text(content, encoding="utf-8")
            output_dir = fallback
    print(f"Created {len(commands)} desktop shortcuts in {output_dir}")


def free_stack_setup(args: argparse.Namespace) -> None:
    if not FREE_STACK_COMPOSE.exists():
        raise SystemExit(f"Free stack compose file not found: {FREE_STACK_COMPOSE}")

    env_map = _ensure_free_stack_env(force_rotate_passwords=bool(getattr(args, "rotate_passwords", False)))
    if bool(getattr(args, "shortcuts", False)):
        _create_free_stack_shortcuts(env_map)

    should_pull = bool(getattr(args, "pull", True))
    should_start = bool(getattr(args, "start", False))
    if should_pull or should_start:
        compose = _detect_compose_base()
        print(f"Using compose runtime: {' '.join(compose)}")

        if should_pull:
            pull = _run_compose(compose, ["pull"], env_file=FREE_STACK_ENV_FILE)
            if pull.returncode != 0:
                raise SystemExit("Failed to download free stack images. Check container runtime and internet access.")

        if should_start:
            up = _run_compose(compose, ["up", "-d"], env_file=FREE_STACK_ENV_FILE)
            if up.returncode != 0:
                raise SystemExit("Failed to start free stack containers.")

    _print_free_stack_credential_summary(env_map)
    if bool(getattr(args, "open", False)):
        _open_free_stack_urls(env_map)


def free_stack_start(args: argparse.Namespace) -> None:
    env_map = _ensure_free_stack_env(force_rotate_passwords=False)
    compose = _detect_compose_base()
    up = _run_compose(compose, ["up", "-d"], env_file=FREE_STACK_ENV_FILE)
    if up.returncode != 0:
        raise SystemExit("Failed to start free stack containers.")
    print("Free stack containers started.")
    _print_free_stack_credential_summary(env_map)
    if bool(getattr(args, "open", False)):
        _open_free_stack_urls(env_map)


def free_stack_stop(_: argparse.Namespace) -> None:
    compose = _detect_compose_base()
    down = _run_compose(compose, ["down"], env_file=FREE_STACK_ENV_FILE)
    if down.returncode != 0:
        raise SystemExit("Failed to stop free stack containers.")
    print("Free stack containers stopped.")


def free_stack_open(_: argparse.Namespace) -> None:
    env_map = _ensure_free_stack_env(force_rotate_passwords=False)
    _open_free_stack_urls(env_map)
    _print_free_stack_credential_summary(env_map)


def free_stack_status(_: argparse.Namespace) -> None:
    compose = _detect_compose_base()
    ps = _run_compose(compose, ["ps"], env_file=FREE_STACK_ENV_FILE)
    if ps.returncode != 0:
        raise SystemExit("Failed to read free stack status.")


def free_stack_install_runtime(args: argparse.Namespace) -> None:
    runtime = str(getattr(args, "runtime", "podman")).strip().lower()
    winget = shutil.which("winget")
    if not winget:
        raise SystemExit(
            "winget is not available on this machine. Install Docker/Podman manually and rerun free-stack setup."
        )

    package_id = "RedHat.Podman-Desktop" if runtime == "podman" else "Docker.DockerDesktop"
    cmd = [
        winget,
        "install",
        "--id",
        package_id,
        "-e",
        "--accept-package-agreements",
        "--accept-source-agreements",
    ]
    print(f"Installing runtime via winget: {package_id}")
    result = subprocess.run(cmd, cwd=REPO_ROOT, text=True, check=False)
    if result.returncode != 0:
        raise SystemExit(f"Runtime install command failed for {package_id}.")
    print(f"Runtime install command completed for {package_id}.")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Agent Space lifecycle utility.")
    parser.add_argument("--host", default="0.0.0.0")
    parser.add_argument("--backend-port", type=int, default=8000)
    parser.add_argument("--frontend-port", type=int, default=5173)
    parser.add_argument("--frontend-runtime", choices=["static", "dev"], default="dev")
    parser.add_argument("--model", default="qwen2.5-coder:14b")
    parser.add_argument("--command-profile", default="safe", choices=["safe", "dev", "unrestricted"])
    parser.add_argument("--review-gate", dest="review_gate", action="store_true", default=True)
    parser.add_argument("--no-review-gate", dest="review_gate", action="store_false")
    parser.add_argument("--allow-shell", action="store_true", default=False)
    parser.add_argument("--max-actions", type=int, default=40)
    parser.add_argument("--max-seconds", type=int, default=1200)
    parser.add_argument("--desktop-mode", action="store_true", default=False)
    parser.add_argument("--create-git-checkpoint", action="store_true", default=False)
    parser.add_argument("--proactive-enabled", action="store_true", default=False)
    parser.add_argument("--proactive-tick-seconds", type=int, default=5)
    parser.add_argument("--n8n-port", type=int, default=5678)
    parser.add_argument("--n8n-url", default="")
    parser.add_argument("--n8n-command", default="")
    parser.add_argument("--n8n-auto-start", action="store_true", default=False)

    sub = parser.add_subparsers(dest="command", required=True)
    start = sub.add_parser("start", help="Start backend + frontend.")
    start.add_argument("--open", action="store_true", default=False)
    start.add_argument("--with-n8n", action="store_true", default=False)
    start.add_argument(
        "--free-ports",
        action="store_true",
        default=False,
        help="If the backend port is taken but /health fails, terminate listener PIDs and retry once.",
    )

    sub.add_parser("stop", help="Stop recorded Agent Space processes.")
    sub.add_parser("open-ui", help="Open UI in browser.")
    desktop = sub.add_parser("desktop", help="Start desktop app shell.")
    desktop.add_argument("--with-services", action="store_true", default=False)
    desktop.add_argument("--with-n8n", action="store_true", default=False)
    desktop.add_argument(
        "--free-ports",
        action="store_true",
        default=False,
        help="If the backend port is taken but /health fails, terminate listener PIDs and retry once.",
    )
    sub.add_parser("shortcuts", help="Create desktop shortcut .cmd files.")

    free_setup = sub.add_parser(
        "free-stack-setup",
        help="Download and configure free local stack services with local accounts.",
    )
    free_setup.add_argument("--start", action="store_true", default=True)
    free_setup.add_argument("--no-start", dest="start", action="store_false")
    free_setup.add_argument("--pull", action="store_true", default=True)
    free_setup.add_argument("--no-pull", dest="pull", action="store_false")
    free_setup.add_argument("--open", action="store_true", default=False)
    free_setup.add_argument("--shortcuts", action="store_true", default=True)
    free_setup.add_argument("--no-shortcuts", dest="shortcuts", action="store_false")
    free_setup.add_argument("--rotate-passwords", action="store_true", default=False)

    free_start = sub.add_parser("free-stack-start", help="Start free local stack containers.")
    free_start.add_argument("--open", action="store_true", default=False)
    sub.add_parser("free-stack-stop", help="Stop free local stack containers.")
    sub.add_parser("free-stack-open", help="Open free stack dashboards in browser.")
    sub.add_parser("free-stack-status", help="Show free stack container status.")
    free_install = sub.add_parser("free-stack-install-runtime", help="Install Docker/Podman runtime via winget.")
    free_install.add_argument("--runtime", choices=["podman", "docker"], default="podman")
    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()
    ensure_runtime_dir()

    if args.command == "start":
        start_services(args)
    elif args.command == "stop":
        stop_services(args)
    elif args.command == "open-ui":
        open_ui(args)
    elif args.command == "desktop":
        start_desktop(args)
    elif args.command == "shortcuts":
        create_shortcuts(args)
    elif args.command == "free-stack-setup":
        free_stack_setup(args)
    elif args.command == "free-stack-start":
        free_stack_start(args)
    elif args.command == "free-stack-stop":
        free_stack_stop(args)
    elif args.command == "free-stack-open":
        free_stack_open(args)
    elif args.command == "free-stack-status":
        free_stack_status(args)
    elif args.command == "free-stack-install-runtime":
        free_stack_install_runtime(args)
    else:
        parser.error(f"Unknown command: {args.command}")


if __name__ == "__main__":
    main()
