"""Static repository audit for jimAI.

Date: 2026-03-09
Purpose: Find common quality/security issues and emit a markdown report.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re
from typing import Iterable


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "docs" / "AUDITOR_ISSUES.md"

SKIP_DIRS = {
    ".git",
    ".venv",
    "node_modules",
    "__pycache__",
    "dist",
    "build",
    "chroma_db",
}

TEXT_SUFFIXES = {
    ".py",
    ".ts",
    ".tsx",
    ".js",
    ".jsx",
    ".json",
    ".md",
    ".txt",
    ".yml",
    ".yaml",
    ".ps1",
    ".cjs",
}

PATTERNS: list[tuple[str, str, str]] = [
    ("HIGH", "Hardcoded secret marker", r"(?i)(api[_-]?key|secret|password|token)\s*[:=]\s*['\"][^'\"]{6,}['\"]"),
    ("MEDIUM", "TODO/FIXME/HACK marker", r"(?i)\b(TODO|FIXME|HACK)\b"),
    ("LOW", "Debug print/console", r"(?i)\b(console\.log|print\s*\()"),
]


@dataclass
class Finding:
    severity: str
    kind: str
    path: str
    line: int
    excerpt: str


def iter_repo_files() -> Iterable[Path]:
    for path in ROOT.rglob("*"):
        if not path.is_file():
            continue
        rel_parts = path.relative_to(ROOT).parts
        if any(part in SKIP_DIRS for part in rel_parts):
            continue
        if path.suffix.lower() not in TEXT_SUFFIXES:
            continue
        yield path


def scan() -> list[Finding]:
    findings: list[Finding] = []
    regexes = [(sev, kind, re.compile(pattern)) for sev, kind, pattern in PATTERNS]
    for path in iter_repo_files():
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except Exception:
            continue
        rel = path.relative_to(ROOT).as_posix()
        for idx, line in enumerate(text.splitlines(), start=1):
            for severity, kind, regex in regexes:
                if regex.search(line):
                    findings.append(
                        Finding(
                            severity=severity,
                            kind=kind,
                            path=rel,
                            line=idx,
                            excerpt=line.strip()[:220],
                        )
                    )
    return findings


def write_report(findings: list[Finding]) -> None:
    by_severity = {"HIGH": [], "MEDIUM": [], "LOW": []}
    for row in findings:
        by_severity.setdefault(row.severity, []).append(row)

    lines: list[str] = []
    lines.append("# Auditor Issues")
    lines.append("")
    lines.append("Generated by `scripts/repo_audit_static.py`.")
    lines.append("")
    lines.append(f"- Total findings: {len(findings)}")
    for sev in ("HIGH", "MEDIUM", "LOW"):
        lines.append(f"- {sev}: {len(by_severity.get(sev, []))}")
    lines.append("")

    for sev in ("HIGH", "MEDIUM", "LOW"):
        rows = by_severity.get(sev, [])
        lines.append(f"## {sev}")
        lines.append("")
        if not rows:
            lines.append("No findings.")
            lines.append("")
            continue
        for row in rows[:500]:
            lines.append(
                f"- [{row.path}:{row.line}] {row.kind} -> `{row.excerpt}`"
            )
        if len(rows) > 500:
            lines.append(f"- ... truncated {len(rows) - 500} additional {sev} findings")
        lines.append("")

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    findings = scan()
    write_report(findings)
    print(f"Wrote {OUTPUT} with {len(findings)} findings")


if __name__ == "__main__":
    main()
